version: 0.0
os: linux

files:
  - source: /
    destination: /deployment

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root