version: 0.0
os: linux

files:
  - source: /requirements.txt
    destination: /var/www/html/

file_exists_behaviour: OVERWRITE

permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root