version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/

file_exists_behaviour: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root