name: Deploy to Amazon EC2

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1             # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Set up Python and Docker
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    # Set up Python and Docker
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy SSH private key to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # Verify SSH connectivity to the EC2 instance
    - name: Verify SSH connectivity
      run: |
        ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }} exit

    # Pull the latest Docker image
    - name: Pull Docker image
      run: |
        ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }} 'docker pull hiadithere/youtube-sentiment-analysis:0.0.7.RELEASE'

    # Verify if the Docker container is running
    - name: Check Docker container status
      run: |
        ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USERNAME }}@${{ secrets.IP_ADDRESS }} 'docker ps'